// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbc

import (
	"time"
)

type Group struct {
	Uuid        string     `json:"uuid"`
	CreatedAt   *time.Time `json:"created_at"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
}

type GroupMember struct {
	Uuid      string `json:"uuid"`
	GroupUuid string `json:"group_uuid"`
	UserUuid  string `json:"user_uuid"`
}

type Transaction struct {
	Uuid        string     `json:"uuid"`
	CreatedAt   *time.Time `json:"created_at"`
	Type        string     `json:"type"`
	Description string     `json:"description"`
	Amount      int64      `json:"amount"`
	Date        time.Time  `json:"date"`
	PaidBy      string     `json:"paid_by"`
	GroupUuid   *string    `json:"group_uuid"`
}

type TransactionParticipant struct {
	Uuid     string `json:"uuid"`
	TxnUuid  string `json:"txn_uuid"`
	UserUuid string `json:"user_uuid"`
	Share    int64  `json:"share"`
}

type User struct {
	Uuid      string     `json:"uuid"`
	CreatedAt *time.Time `json:"created_at"`
	Name      string     `json:"name"`
	VenmoID   *string    `json:"venmo_id"`
}
