// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbc

import (
	"time"
)

type GroupMember struct {
	ID      []byte `json:"id"`
	GroupID []byte `json:"group_id"`
	UserID  []byte `json:"user_id"`
}

type GroupRaw struct {
	ID          []byte     `json:"id"`
	CreatedAt   *time.Time `json:"created_at"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
}

type TransactionParticipant struct {
	ID     []byte `json:"id"`
	TxnID  []byte `json:"txn_id"`
	UserID []byte `json:"user_id"`
	Share  int64  `json:"share"`
}

type TransactionRaw struct {
	ID          []byte     `json:"id"`
	CreatedAt   *time.Time `json:"created_at"`
	Type        string     `json:"type"`
	Description string     `json:"description"`
	Amount      int64      `json:"amount"`
	Date        time.Time  `json:"date"`
	PaidBy      []byte     `json:"paid_by"`
	GroupID     []byte     `json:"group_id"`
}

type User struct {
	ID        []byte     `json:"id"`
	CreatedAt *time.Time `json:"created_at"`
	Name      string     `json:"name"`
	VenmoID   *string    `json:"venmo_id"`
}
