// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
insert into Groups (
    uuid
    , name
    , description
) values (
    ?1
    , ?2
    , ?3
) returning uuid, name, description
`

type CreateGroupParams struct {
	Uuid        string  `json:"uuid"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Uuid, arg.Name, arg.Description)
	var i Group
	err := row.Scan(&i.Uuid, &i.Name, &i.Description)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
insert into Transactions (
    uuid
    , type
    , description
    , amount
    , date
    , paid_by
    , group_uuid
) values (
    ?1
    , ?2
    , ?3
    , ?4
    , ?5
    , ?6
    , ?7
) returning uuid, type, description, amount, date, paid_by, group_uuid
`

type CreateTransactionParams struct {
	Uuid        string  `json:"uuid"`
	Type        string  `json:"type"`
	Description string  `json:"description"`
	Amount      int64   `json:"amount"`
	Date        int64   `json:"date"`
	PaidBy      string  `json:"paid_by"`
	GroupUuid   *string `json:"group_uuid"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Uuid,
		arg.Type,
		arg.Description,
		arg.Amount,
		arg.Date,
		arg.PaidBy,
		arg.GroupUuid,
	)
	var i Transaction
	err := row.Scan(
		&i.Uuid,
		&i.Type,
		&i.Description,
		&i.Amount,
		&i.Date,
		&i.PaidBy,
		&i.GroupUuid,
	)
	return i, err
}

const createTransactionParticipant = `-- name: CreateTransactionParticipant :one
insert into TransactionParticipants (
    uuid
    , txn_uuid
    , user_uuid
    , share
) values (
    ?1
    , ?2
    , ?3
    , ?4
) returning uuid, txn_uuid, user_uuid, share
`

type CreateTransactionParticipantParams struct {
	Uuid     string `json:"uuid"`
	TxnUuid  string `json:"txn_uuid"`
	UserUuid string `json:"user_uuid"`
	Share    int64  `json:"share"`
}

func (q *Queries) CreateTransactionParticipant(ctx context.Context, arg CreateTransactionParticipantParams) (TransactionParticipant, error) {
	row := q.db.QueryRowContext(ctx, createTransactionParticipant,
		arg.Uuid,
		arg.TxnUuid,
		arg.UserUuid,
		arg.Share,
	)
	var i TransactionParticipant
	err := row.Scan(
		&i.Uuid,
		&i.TxnUuid,
		&i.UserUuid,
		&i.Share,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into Users (
    uuid
    , name
    , venmo_id
) values (
    ?1
    , ?2
    , ?3
) returning uuid, name, venmo_id
`

type CreateUserParams struct {
	Uuid    string  `json:"uuid"`
	Name    string  `json:"name"`
	VenmoID *string `json:"venmo_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Uuid, arg.Name, arg.VenmoID)
	var i User
	err := row.Scan(&i.Uuid, &i.Name, &i.VenmoID)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
delete from Groups
where
    uuid = ?1
`

func (q *Queries) DeleteGroup(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, uuid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from Users
where
    uuid = ?1
`

func (q *Queries) DeleteUser(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, uuid)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
select
    uuid, name, description
from
    Groups
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
select
    uuid, name, venmo_id
from
    Users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Uuid, &i.Name, &i.VenmoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebts = `-- name: GetDebts :many
with net_owed as (
    select 
        tp.user_uuid as debtor
        , t.paid_by as creditor
        , sum(tp.share) as amount_owed
    from
        TransactionParticipants tp
    join
        Transactions t on tp.txn_uuid = t.uuid
    where
        t.type = 'expense' 
        and tp.user_uuid <> t.paid_by
    group by
        tp.user_uuid, t.paid_by
), aggregate_net_owed as (
    select
        debtor_net_owed.debtor
        , debtor_net_owed.creditor
        , sum(debtor_net_owed.amount_owed - coalesce(creditor_net_owed.amount_owed, 0)) as net_amount
    from
        net_owed debtor_net_owed
    left join
        net_owed creditor_net_owed 
        on debtor_net_owed.debtor = creditor_net_owed.creditor 
        and debtor_net_owed.creditor = creditor_net_owed.debtor
    group by
        debtor_net_owed.debtor, debtor_net_owed.creditor
)
select 
    debtor
    , creditor
    , cast(net_amount as integer)
from 
    aggregate_net_owed
where
    net_amount > 0
`

type GetDebtsRow struct {
	Debtor    string `json:"debtor"`
	Creditor  string `json:"creditor"`
	NetAmount int64  `json:"net_amount"`
}

func (q *Queries) GetDebts(ctx context.Context) ([]GetDebtsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDebts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtsRow
	for rows.Next() {
		var i GetDebtsRow
		if err := rows.Scan(&i.Debtor, &i.Creditor, &i.NetAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroup = `-- name: GetGroup :one
select
    uuid, name, description
from
    Groups
where
    uuid = ?1
`

func (q *Queries) GetGroup(ctx context.Context, uuid string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, uuid)
	var i Group
	err := row.Scan(&i.Uuid, &i.Name, &i.Description)
	return i, err
}

const getUser = `-- name: GetUser :one
select
    uuid, name, venmo_id
from
    Users
where
    uuid = ?1
`

func (q *Queries) GetUser(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, uuid)
	var i User
	err := row.Scan(&i.Uuid, &i.Name, &i.VenmoID)
	return i, err
}
